### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Michael-E-Rose** [markwestcott34/stargazer-booktabs#1]
It's pretty unclear what one has to do to use this library.  Spare some details in the README.md?

**Comment by markwestcott34** [comment]
Closed by 4bc4f5be95584c38ebfa8554b3c4bc8d6c4b9847

**Comment by markwestcott34** [comment]
I've added some example output in https://github.com/markwestcott34/stargazer-booktabs/blob/master/vignettes/stargazer-booktabs.pdf
