### ISSUE TITLE
format.alignment error for data frame with summary=FALSE

### ISSUE THREAD

**Issue by linoferreira** [markwestcott34/stargazer-booktabs#6]
When using `stargazer-booktabs` to output a LaTeX table reproducing the contents of a data frame (so with the `summary` option set to `FALSE`) I get the following error:

```
Error in paste(.formatting.alignment, "c", sep = "") : 
  object '.formatting.alignment' not found
```

Here is a simple example to illustrate the issue:

```
> df <- data.frame(Name = c("John", "Abigail", "Paul"),
+                  Age  = c(30, 25, 49))
> stargazer(df, summary=FALSE)

% Table created by stargazer v.5.2 by Marek Hlavac, Harvard University. E-mail: hlavac at fas.harvard.edu
% Date and time: Fri, Jul 27, 2018 - 12:58:39
\begin{table}[!htbp] \centering 
  \caption{} 
  \label{} 
Error in paste(.formatting.alignment, "c", sep = "") : 
  object '.formatting.alignment' not found
```

The code above works fine prior to installing `stargazer-booktabs`. I did a clean install of both `stargazer` and `stargazer-booktabs` today prior to running this code. In the past I've had no issues with `stargazer-booktabs` for regression output.

Thank you very much for your time and for this very useful fork!

**Comment by markwestcott34** [comment]
Hi @linoferreira  -- thanks for the report. I'll look into this!

**Comment by markwestcott34** [comment]
Hi @l-ferreira -- that should be fixed. Thanks for using stargazer-booktabs!

**Comment by linoferreira** [comment]
It works fine now, thank you very much for fixing the issue so quickly!
